/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.telas;

import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import main.classes.menu.GaragemCarro;
import main.classes.produtos.Carro;

/**
 *
 * @author EAS
 */
public class GerenciarPedidos extends javax.swing.JFrame {
    private GaragemCarro garagem = GaragemCarro.getInstance();
    private int i;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarPedidos.class.getName());

    /**
     * Creates new form GerenciarCarros
     * @param i
     */
    
    public GerenciarPedidos(int i) {
        this.i = i;
        initComponents();
    }

    public GerenciarPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PainelP = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        Disponivel = new javax.swing.JRadioButton();
        Indefinido = new javax.swing.JRadioButton();
        Dispensado = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPlaca.setText("Gerenciar tamanho do pedido:");

        buttonGroup1.add(Disponivel);
        Disponivel.setText("Disponivel");
        Disponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponivelActionPerformed(evt);
            }
        });

        buttonGroup1.add(Indefinido);
        Indefinido.setText("Indefinido");

        buttonGroup1.add(Dispensado);
        Dispensado.setText("Dispensado");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPLayout = new javax.swing.GroupLayout(PainelP);
        PainelP.setLayout(PainelPLayout);
        PainelPLayout.setHorizontalGroup(
            PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Disponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Indefinido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dispensado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlaca))
                        .addGap(0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelPLayout.setVerticalGroup(
            PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Disponivel)
                .addGap(18, 18, 18)
                .addComponent(Indefinido)
                .addGap(18, 18, 18)
                .addComponent(Dispensado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Carro> carros = garagem.getListaCarros();
        Carro carro = carros.get(this.i);
        switch(carro.getStatus()){
            case "Disponivel":
                Disponivel.setSelected(true);
                break;
            case "Manutencao":
                Indefinido.setSelected(true);
                break;
            case "Alugado":
                Dispensado .setSelected(true);
                break;
        }
        lblPlaca.setText(lblPlaca.getText() + ' ' + carro.getPlaca());
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String status = "";
        for(Enumeration<AbstractButton> botoes = buttonGroup1.getElements(); botoes.hasMoreElements();){
            AbstractButton btn = botoes.nextElement();
            if (btn.isSelected()) status = btn.getText();
        }
        Carro carro = garagem.getListaCarros().get(this.i);
        carro.setStatus(status);
        garagem.editarCarro(carro, this.i);
        JOptionPane.showMessageDialog(null, "Status alterado com sucesso!", "Info", 1);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisponivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GerenciarPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Dispensado;
    private javax.swing.JRadioButton Disponivel;
    private javax.swing.JRadioButton Indefinido;
    private javax.swing.JPanel PainelP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPlaca;
    // End of variables declaration//GEN-END:variables
}
